config:
  - name: test-server-1
    remote: local
    project: default
    launch:
      image: 
        remote: images
        name: ubuntu/22.04
        
  - name: test-server-2
    remote: local
    project: default
    launch:
      image: 
        remote: images
        name: ubuntu/22.04