config:
  - name: test-server-1
    remote: nsec-cloud
    project: ringzer0
    launch:
      image: 
        remote: images
        name: ubuntu/22.04
        
  - name: test-server-2
    remote: nsec-cloud
    project: ringzer0
    launch:
      image: 
        remote: images
        name: ubuntu/22.04